#!/usr/bin/env bash
set -x

cflags=(-g3 -Wall -Wextra -Wpedantic -Werror -fsanitize=undefined,address -fno-strict-aliasing)
ldflags=(-lraylib)

gcc -c $cflags ./src/hotreload.c -o ./obj/hot_reload.o
gcc -c $cflags ./src/main.c -o ./obj/main.o

gcc ./obj/main.o ./obj/hot_reload.o -o ./bin/main $ldflags

./hotreload
