#!/usr/bin/env bash
set -x

cflags=(-g3 -Wall -Wextra -Wpedantic -Werror -fsanitize=undefined,address -fno-strict-aliasing)
ldflags=(-lraylib)

gcc -c -fPIC $cflags ./src/color_picker.c -o ./obj/color_picker.o
gcc -shared ./obj/color_picker.o -o ./bin/libcolor_picker.so $ldflags

gcc -c $cflags ./src/main.c -o ./obj/main.o
gcc ./obj/main.o -o ./bin/main $ldflags
